apiVersion: v1
kind: Service
metadata:
  name: {{ include "bulletin-deploy.fullname" . }}
  labels:
    {{- include "bulletin-deploy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
      nodePort: {{ .Values.service.node_port }}
      protocol: TCP
      name: http
  selector:
    {{- include "bulletin-deploy.selectorLabels" . | nindent 4 }}
